report:
	pdflatex LaTeX_Tutorial.tex
	pdflatex LaTeX_Tutorial.tex
	#dvipdf LaTeX_Tutorial

clean:
	rm LaTeX_Tutorial.aux
	rm LaTeX_Tutorial.log
	rm LaTeX_Tutorial.out
	rm LaTeX_Tutorial.pdf
	rm LaTeX_Tutorial.toc
